---

- name: Check EPEL repository
  shell: 'yum repolist | grep ^epel | cut -f1 -d" "'
  register: epel_enabled
  changed_when: false
  tags:
   - install
   - nginx

- name: Downloading and enable the EPEL 6 repository definitions.
  action: command rpm -Uvh --replacepkgs http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
  when: ansible_distribution_major_version == 6 and epel_enabled.stdout.startswith('epel')
  tags:
   - install
   - nginx

- name: Downloading and enable the EPEL 7 repository definitions.
  yum: name=epel-release state=present
  when: ansible_distribution_major_version == 7 and epel_enabled.stdout.startswith('epel')
  tags:
   - install
   - nginx

- name: Install nginx web server for RedHat derivatives
  yum: name={{ item }} state=present
  with_items:
   - nginx
  tags:
   - install
   - nginx

- name: Remove default server
  file: name=/etc/nginx/conf.d/default.conf state=absent
  tags:
    - install
    - nginx

- name: Set log directory permissions
  file: path={{webserver_nginx_log_directory}} owner={{webserver_user}}
        group={{webserver_group}} state=directory recurse=yes mode=0750
  tags:
    - configure
    - nginx

- name: Set lib directory permissions
  file: path={{webserver_nginx_lib_directory}} owner={{webserver_user}}
        group={{webserver_group}} state=directory recurse=yes mode=0750
  tags:
    - configure
    - nginx

- name: Set nginx.conf file
  template: src=nginx-config.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644 backup=yes
  notify:
   - test nginx and restart
  tags:
   - configure
   - nginx

- name: Set up virtual hosts
  template: src=nginx-site.conf.j2 dest="/etc/nginx/conf.d/{{ item }}.conf"
      owner=root group=root mode=0644
  with_items: webserver_sites.keys()
  notify:
   - test nginx and reload
  tags:
   - configure
   - nginx

- name: Start and enable nginx web server for RedHat derivatives
  service: name=nginx state=started enabled=yes
  tags:
   - install
   - nginx
